# Generated by Django 4.2 on 2024-12-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course', 'status')},
        ),
    ]
