# Generated by Django 4.2 on 2024-12-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_userprogress_progress_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizanswer',
            name='selected_option_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
