# Generated by Django 4.2 on 2024-12-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_userquizanswer_selected_option_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizanswer',
            name='selected_option_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
