# Generated by Django 4.2 on 2024-12-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_userquizanswer_selected_option_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquizanswer',
            name='selected_option_text',
        ),
    ]
