version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django-network

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=task_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
    networks:
      - django-network

volumes:
  postgres_data:
  static_volume:

networks:
  django-network: